# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moribito < Formula
  desc "LDAP CLI Explorer - Interactive terminal-based LDAP client with TUI"
  homepage "https://github.com/ericschmar/moribito"
  version "0.2.6"
  license "MIT"

  on_macos do
    url "https://github.com/ericschmar/moribito/releases/download/v0.2.6/moribito_Darwin_x86_64.tar.gz"
    sha256 "674ee1a4cbf2a6792fba74e9f52c9ddbba76346461963c665897af200b6a8619"

    def install
      bin.install "moribito"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Moribito
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ericschmar/moribito/releases/download/v0.2.6/moribito_Linux_x86_64.tar.gz"
      sha256 "604900a6d0e75c6a0c0e9be1a6b17c3199a52f28d4bb3c235daa25cbacaa243d"
      def install
        bin.install "moribito"
      end
    end
  end

  test do
    system "#{bin}/moribito --version"
  end
end
