# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moribito < Formula
  desc "LDAP CLI Explorer - Interactive terminal-based LDAP client with TUI"
  homepage "https://github.com/ericschmar/moribito"
  version "0.2.6"
  license "MIT"

  on_macos do
    url "https://github.com/ericschmar/moribito/releases/download/v0.2.6/moribito_Darwin_x86_64.tar.gz"
    sha256 "4a9a07d01c88d39404da648f9670a0e58d088b5e80ff362daf3f5b307d75f971"

    def install
      bin.install "moribito"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Moribito
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ericschmar/moribito/releases/download/v0.2.6/moribito_Linux_x86_64.tar.gz"
      sha256 "242051101d3ea8b842b16aee3d092d4a8217b3f40322f6bb36cbfb74c01ae186"
      def install
        bin.install "moribito"
      end
    end
  end

  test do
    system "#{bin}/moribito --version"
  end
end
