# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moribito < Formula
  desc "LDAP CLI Explorer - Interactive terminal-based LDAP client with TUI"
  homepage "https://github.com/ericschmar/moribito"
  version "0.2.5"
  license "MIT"

  on_macos do
    url "https://github.com/ericschmar/moribito/releases/download/v0.2.5/moribito_Darwin_x86_64.tar.gz"
    sha256 "131f376b3b2cc17744036c061e0a8b88021b093e45191f7793ffe9dcee345c65"

    def install
      bin.install "moribito"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Moribito
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ericschmar/moribito/releases/download/v0.2.5/moribito_Linux_x86_64.tar.gz"
      sha256 "b8956756b66e887bbf65cdf876eb378728341d1423c302876574787ca6c030f1"
      def install
        bin.install "moribito"
      end
    end
  end

  test do
    system "#{bin}/moribito --version"
  end
end
